# Generated by Django 5.0.4 on 2024-05-07 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_price',
            new_name='price',
        ),
    ]
